---
title: "DATA_605 HW #1"
Author: Alex Khaykin
output: html_document
date: "2024-01-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plotly)
library(animation)
```




```{r}
x_a=c(rep(0,500),seq(0,1,length.out=1000), rep(1,500), seq(0,1,length.out=1000))
y_a=c(seq(-1,1,length.out=500),rep(0,1000), seq(-1,1,length.out=500), rep(1,1000))
z=rbind(x_a,y_a)
plot(y_a~x_a, xlim=c(-3,3), ylim=c(-3,3), col = "blue") 
```

 
```{r}
x_k=c(rep(0,500),seq(1,0,length.out=1000), seq(1,0,length.out=1000))
y_k=c(seq(-1,1,length.out=500),seq(-1,0,length.out=1000), seq(1,0,length.out=1000))
z=rbind(x_k,y_k)
plot(y_k~x_k, xlim=c(-3,3), ylim=c(-3,3), col = "blue")
```

```{r}
x_a_k = c(x_a-1.5, x_k+.25)
y_a_k = c(y_a, y_k)
z=rbind(x_a_k,y_a_k)
plot(y_a_k~x_a_k, xlim=c(-3,3), ylim=c(-3,3), col = "blue")
```


```{r}
identity_matrix = diag(7)
matrix(rep(0,7), nrow = 7, ncol = 7) %*% identity_matrix
left_mult = function(x,y){
  x %*% y
}
left_mult(matrix(rep(0,7), nrow = 7, ncol = 7),identity_matrix)

```



```{r}
x11()

# Create an empty animation recording
anim = ani.record(reset = TRUE, replay.cur = FALSE)

# Loop through each frame
for (i in seq(1, 4, length.out = 40)) {
  # Apply scaling transformation
  # The scaling matrix is [i 0; 0 i]
  z_scaling = apply(z, 2, function(x) left_mult(x, matrix(c(i, 0, 0, i), nrow = 2, ncol = 2)))

  # Plot the scaled points
  plot(z_scaling[2,] ~ z_scaling[1,], xlim = c(-3, 3), ylim = c(-3, 3), col = "blue", main = "Scaling Transformation")
  
  # Record the frame for animation
  ani.record()
}
```

```{r}
x11()
# Create an empty animation recording
anim = ani.record(reset = TRUE, replay.cur = FALSE)

# Loop through each frame
for (i in seq(0, 1, length.out = 40)) {
  # Apply shear transformation
  # The shear matrix is [1 i; 0 1]
  z_shear = apply(z, 2, function(x) left_mult(x, matrix(c(1, i, 0, 1), nrow = 2, ncol = 2)))

  # Plot the sheared points
  plot(z_shear[2,] ~ z_shear[1,], xlim = c(-3, 3), ylim = c(-3, 3), col = "blue", main = "Shear Transformation")
  
  # Record the frame for animation
  ani.record()
}
```



```{r}
x11()
# Create an empty animation recording
anim = ani.record(reset = TRUE, replay.cur = FALSE)

for (i in seq(0, 1, length.out = 40)) {
  # Apply rotation transformation
  angle = 360 * i  # Convert i to degrees (360 degrees for a full spin)
  z_rotated = apply(z, 2, function(x) left_mult(x, matrix(c(cos(angle), -sin(angle), sin(angle), cos(angle)), nrow = 2, ncol = 2)))

  # Plot the rotated z_shear
  plot(z_rotated[2,] ~ z_rotated[1,], xlim = c(-3, 3), ylim = c(-3, 3), col = "blue", main = "Rotation Spin")
}
```


```{r}
x11()
# Create an empty animation recording
anim = ani.record(reset = TRUE, replay.cur = FALSE)
num_frames <- 40

# Loop through each frame
for (i in seq(0, 1, length.out = num_frames)) {
  # Apply rotation transformation
  angle <- 360 * i  # Convert i to degrees (360 degrees for a full spin)
  z_rotated <- apply(z, 2, function(x) left_mult(x, matrix(c(cos(angle), -sin(angle), sin(angle), cos(angle)), nrow = 2, ncol = 2)))

  # Project the rotated points onto the XY plane (2D projection)
  z_projected <- z_rotated[1:2, ]  # Keep only the first two dimensions
# Plot the projected points
  plot(z_projected[2, ] ~ z_projected[1, ], xlim = c(-3, 3), ylim = c(-3, 3), col = "blue", main = "2D Projection")
  
  # Record the frame for animation
  ani.record()
}

```

